config:
  dockerfile: .woloxci/Dockerfile
  project_name: conduitReactNative

steps:
  lint:
    - ln -sfn /home/node/node_modules node_modules
    - cd && npm run lint
    - cd && npm run check-types
    - cd && npm run test

environment:
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
